services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "9090:8080"   # Jenkins web UI
      - "50000:50000" # Jenkins agent port
    environment:
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=myStrongPassword123
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
